name: DLT Jaffle Shop Pipeline

on:
  workflow_dispatch:  # Hiermee kun je de workflow handmatig starten
  schedule:
    - cron: '0 0 * * *'  # Optioneel: dagelijks om middernacht uitvoeren

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install dlt duckdb
      
      - name: Run DLT pipeline
        run: python jaffle_shop_pipeline.py
